% Generated by MATLAB(R) 26.1 (R2026a) and Satellite Communications Toolbox 26.1 (R2026a).
% Generated on: 12-May-2026 19:45:43
%%This is the code used for phase 1, which is the small model used for the
%%inital test
clc
clear
close all
%% Link Details input
% Link         L1 L2 L3
% Transmitter  G1 S2 S3
% Receiver     S1 G2 S4

% Ground station (G1) properties
g1.Latitude = 40.4314; % deg
g1.Longitude = -4.2481; % deg
g1.Altitude = 800; % m
% Satellite (S1) properties
s1.Latitude = 40.4314; % deg
s1.Longitude = -4.2481; % deg
s1.Altitude = 384400; % km

% Ground station (G1) transmitter properties
tx1.TxFeederLoss = 1; % dB
tx1.OtherTxLosses = 1; % dB
tx1.TxHPAPower = 17; % dBW
tx1.TxHPAOBO = 4; % dB
tx1.TxAntennaGain = 25; % dBi

% Satellite (S1) receiver properties
rx1.InterferenceLoss = 2; % dB
rx1.RxGByT = 15; % dB/K
rx1.RxFeederLoss = 1; % dB
rx1.OtherRxLosses = 1; % dB

% Link (L1) properties
%l1.Frequency = 8; % GHz
l1.Bandwidth = 4; % MHz
l1.BitRate = 0.001; % Mbps
l1.RequiredEbByNo = 10.384; % dB
l1.PolarizationMismatch = 45; % deg
l1.ImplementationLoss = 2; % dB
l1.AntennaMispointingLoss = 1; % dB
l1.RadomeLoss = 1; % dB

%% 

% change l1 frequency

%% Change L1 frequency and plot link margin

freqSweep = 8:0.1:12;              % GHz
margin = zeros(size(freqSweep));   % pre-allocate margin array

for i = 1:numel(freqSweep)

    % Copy original link parameters
    l1_i = l1;

    % Change frequency for this iteration
    l1_i.Frequency = freqSweep(i); % GHz

    % Calculate link budget
    res = calculateLinkBudget(g1, s1, tx1, rx1, l1_i);
    % Store result
    margin(i) = res.Margin;

    % Optional: print result in Command Window
    fprintf('Frequency = %.1f GHz, Margin = %.2f dB\n', ...
            freqSweep(i), margin(i));
end

% Plot result
figure;
plot(freqSweep, margin, 'LineWidth', 1.5);
xlabel('Frequency (GHz)');
ylabel('Link Margin (dB)');
title('L1 Link Margin vs Frequency');
grid on;


%% This part for finding the best value when frequency changes
%L1 uplink


%% display the result

colName = {'Tag','Name', 'L1','L2','L3'};
colWidthData = 2*(10-3*1.5 -1);
width = strcat(num2str(colWidthData),'x');
ColumnWidth = {'2x',width,'3x'};
colFormat = {'char','char','numeric'};
res = [res1 res2 res3];
data = {'N1','Distance (km)',res.Distance;...
    'N2','Elevation (deg)',res.Elevation;...
    'N3','Tx EIRP (dBW)',res.TxEIRP;...
    'N4','Polarization loss (dB)',res.PolarizationLoss;...
    'N5','FSPL (dB)',res.FSPL;...
    'N6','Received isotropic power (dBW)',res.ReceivedIsotropicPower;...
    'N7','C/No (dB-Hz)',res.CByNo;...
    'N8','C/N (dB)',res.CByN;...
    'N9','Received Eb/No (dB)',res.ReceivedEbByNo;...
    'N10','Margin (dB)',res.Margin};
fig = uifigure('Name','Link Budget');
uit = uitable(fig,'units','normalized',...
    'Position',[0 0 1 1],'RowName',{},...
    'ColumnName',colName,'ColumnWidth',ColumnWidth,...
    'ColumnFormat',colFormat,'Data',data);

%% FSPL line plot
nData = 9;
midPoint = ceil(nData/2);
xCurrentValue = zeros(length(res),1);
yCurrentValue = zeros(length(res),1);
hFig = uifigure('Name','FSPL');
hAx = axes('Parent', hFig);
spec = {g1;g2;s3};
sat = {s1;s2;s4};
tx = {tx1;tx2;tx3};
rx = {rx1;rx2;rx3};
lnk = {l1;l2;l3};
lnkName = {'L1','L2','L3','Operating Point'};
for ii = 1:length(res)
    yCurrentValue(ii) = res(ii).FSPL;
    xCurrentValue(ii) = res(ii).Distance;
    stepSize = xCurrentValue(ii)/midPoint;
    vectorSpecValue = (1:nData)'* stepSize;
    resultLine = calculateLinkBudget(spec{ii},sat{ii},tx{ii},rx{ii},lnk{ii},'FSPL',vectorSpecValue);
    plot(hAx,resultLine.Distance,resultLine.FSPL);
    hold(hAx,'on');
    grid(hAx,'on');
end


%% Margin contour plot
for ii = 1:length(res)
    txContour  = tx{ii};
    xCurrentValue = txContour.TxHPAPower;
    xStepSize = xCurrentValue/midPoint;
    if stepSize == 0
        xValues = -1*floor(nData/2):floor(nData/2);
        txContour.TxHPAPower = xValues(1:nData);
    else
        txContour.TxHPAPower = sort((1:nData) * xStepSize);
    end
    yCurrentValue = res(ii).Distance;
    yStepSize = yCurrentValue/midPoint;
    vectorSpecValue = (1:nData)'* yStepSize;
    resultContour = calculateLinkBudget(spec{ii},sat{ii},txContour,rx{ii},lnk{ii},'Margin',vectorSpecValue);
    hFig = uifigure('Name',['Margin - ' lnkName{ii}]);
    hAx = axes('Parent', hFig);
    grid(hAx,'on');
    contour(hAx,txContour.TxHPAPower,resultContour.Distance,resultContour.Margin,'ShowText','on');
    hold(hAx,'on');
    plot(hAx,xCurrentValue,yCurrentValue, 'r*');
    legend(hAx,{'Margin (dB)', 'Operating Point'});
    hAx.XLabel.String = 'Tx HPA power (dBW)';
    hAx.YLabel.String = 'Distance (km)';
    hAx.ZLabel.String = 'Margin (dB)';
end

%% Local function for calculating link budget
%do not touch
function res = calculateLinkBudget(spec,sat,tx,rx,lnk,varargin)
assignin("base","struct1",spec);
assignin("base","struct2",sat);
assignin("base","struct3",tx);
assignin("base","struct4",rx);
assignin("base","struct5",lnk);
resultProperty = [];
resultVariable = [];
if nargin > 5
    resultVariable = varargin{1};
end
if nargin == 8
    resultProperty = varargin{2};
    resultValue = varargin{3};
end
params = {"Distance";"Elevation";"TxEIRP";"PolarizationLoss";...
    "FSPL";"ReceivedIsotropicPower";"CByNo";"CByN";...
    "ReceivedEbByNo";"Margin"};
eqns = {"satcom.internal.linkbudgetApp.computeDistance(struct1.Latitude, struct1.Longitude, struct1.Altitude, struct2.Latitude, struct2.Longitude, struct2.Altitude*1e3)";...
    "satcom.internal.linkbudgetApp.computeElevation(struct1.Latitude, struct1.Longitude, struct1.Altitude, struct2.Latitude, struct2.Longitude, struct2.Altitude*1e3)";...
    "struct3.TxHPAPower - struct3.TxHPAOBO - struct3.TxFeederLoss - struct3.OtherTxLosses + struct3.TxAntennaGain - struct5.RadomeLoss";...
    "20 * abs(log10(cosd(struct5.PolarizationMismatch)))";...
    "fspl(temp.Distance * 1e3, physconst('LightSpeed') ./ (struct5.Frequency*1e9))";...
    "temp.TxEIRP - temp.PolarizationLoss - temp.FSPL - struct4.InterferenceLoss - struct5.AntennaMispointingLoss";...
    "temp.ReceivedIsotropicPower + struct4.RxGByT - 10*log10(physconst('Boltzmann')) - struct4.RxFeederLoss - struct4.OtherRxLosses";...
    "temp.CByNo - 10*log10(struct5.Bandwidth) - 60";...
    "temp.CByNo - 10*log10(struct5.BitRate) - 60";...
    "temp.ReceivedEbByNo - struct5.RequiredEbByNo - struct5.ImplementationLoss"};
if nargin == 7
    vectorSpecValue = varargin{2};
    eqns{1} = mat2str(vectorSpecValue);
end
for ii = 1:length(params)
    varname = strcat("temp.",params{ii});
    if any(strcmp(resultProperty,params{ii}))
        evalin("base",sprintf("%s = %f;",varname,resultValue(strcmp(resultProperty,params{ii}))))
    else
        evalin("base",sprintf("%s = %s;",varname,eqns{ii}))
    end
    if strcmp(resultVariable,params{ii}) && ~isempty(resultVariable)
        break;
    end
end
res = evalin("base","temp");
evalin("base","clear struct1 struct2 struct3 struct4 struct5 temp");
end

%% Local function for visualizing plot(s)
%do not touch
% Custom 2D line plot
function hFig = custom2DLine(data,info)
spec = data{1};
sat = data{2};
tx = data{3};
rx = data{4};
lnk = data{5};
res = data{6};
items = {'Ground Station','Satellite','Transmitter','Receiver','Link','Results'};
speclist = {'spec','sat','tx','rx','lnk','res'};
xspec = speclist{strcmp(items,info.Xtype)};
xCurrentValue = zeros(length(res),1);
yCurrentValue = zeros(length(res),1);
hFig = uifigure ('Name',info.Name);
hAx = axes('Parent', hFig);

xstr = strsplit(info.Xaxis,' (');
xvar = strsplit(xstr{1},' ');
newstr = cell(length(xvar),1);
for jj = 1:length(xvar)
    if contains(xvar{jj},'/')
        temp = strrep(xvar{jj},'/','By');
    else
        temp = xvar{jj};
    end
    newstr{jj} = [upper(temp(1))  temp(2:end)];
end
xparam = [newstr{:}];

ystr = strsplit(info.Yaxis,' (');
yvar = strsplit(ystr{1},' ');
newstr = cell(length(yvar),1);
for jj = 1:length(yvar)
    if contains(yvar{jj},'/')
        temp = strrep(yvar{jj},'/','By');
    else
        temp = yvar{jj};
    end
    newstr{jj} = [upper(temp(1))  temp(2:end)];
end
yparam = [newstr{:}];

for ii = 1:length(res)
    a = info.Xvalues{ii};
    nData = 5;
    b = (a(2)-a(1))/(nData-1);
    c =  a(1)+(0:nData-1)*b;
    vectorSpecValue = c;
    xVec = zeros(nData,1);
    yVec = zeros(nData,1);
    for  kk = 1 : length(vectorSpecValue)
        if strcmp(xspec,'res')
            eval([xspec '(ii).' xparam '= vectorSpecValue(kk);']);
        else
            eval([xspec '{ii}.' xparam '= vectorSpecValue(kk);']);
        end
        if strcmp(info.Xtype,'Results')
            resCustom = calculateLinkBudget(spec{ii},sat{ii},tx{ii},rx{ii},lnk{ii},...
                yvar,xparam,res(ii).(xparam));
        else
            resCustom = calculateLinkBudget(spec{ii},sat{ii},tx{ii},rx{ii},lnk{ii},yvar);
        end
        yVec(kk) = resCustom.(yparam);
        xVec(kk) = vectorSpecValue(kk);
    end
    xCurrentValue(ii) =  xVec(3);
    yCurrentValue(ii) =  yVec(3);
    plot(hAx,xVec,yVec);
    grid(hAx,'on');
    hold(hAx,'on');
end
plot(hAx,xCurrentValue,yCurrentValue, 'r*');
lnkName = {'L1','L2','L3','Operating Point'};
legend(hAx,lnkName{:}, 'Location', 'southeast');
hAx.XLabel.String = info.Xaxis;
hAx.YLabel.String = info.Yaxis;
end